version: '3.8'

services:
  crypto-monitor:
    build: .
    container_name: crypto-monitor
    restart: unless-stopped

    env_file:
      - .env

    environment:
      - TZ=Asia/Shanghai

    volumes:
      - ./config:/usr/src/app/config
      - ./log:/usr/src/app/log

      # 状态文件统一放进目录
      - ./data:/usr/src/app/data

      # Linux服务器推荐
      - /etc/localtime:/etc/localtime:ro